version: "3.8"

services:
  web:
    build: .
    ports:
      - "5173:5173"  # Viteのデフォルトポート
    volumes:
      - ./metal-metronome:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
    command: npm run dev
